import type { DungeonDefinition, LootTable, MobDefinition, QuestDefinition, QuestGiverDefinition, SpotDefinition, ZoneDefinition } from '../types/game';

// Skeleton expansion content for levels 21-60.
// Rule: one zone per 4 levels, each zone has 2 spots, 4 outdoor mobs, 1 dungeon and 1 quest giver.

export const EXPANSION_LOOT_TABLES: LootTable[] = [
  { id: 'lt_ironwood_frontier', entries: [] },
  { id: 'lt_ironwood_frontier_dungeon', entries: [] },
  { id: 'lt_saltwind_coast', entries: [] },
  { id: 'lt_saltwind_coast_dungeon', entries: [] },
  { id: 'lt_emberfall_badlands', entries: [] },
  { id: 'lt_emberfall_badlands_dungeon', entries: [] },
  { id: 'lt_duskglass_reach', entries: [] },
  { id: 'lt_duskglass_reach_dungeon', entries: [] },
  { id: 'lt_stormpeak_gate', entries: [] },
  { id: 'lt_stormpeak_gate_dungeon', entries: [] },
  { id: 'lt_hollow_star_marsh', entries: [] },
  { id: 'lt_hollow_star_marsh_dungeon', entries: [] },
  { id: 'lt_crimson_obelisk', entries: [] },
  { id: 'lt_crimson_obelisk_dungeon', entries: [] },
  { id: 'lt_pale_king_road', entries: [] },
  { id: 'lt_pale_king_road_dungeon', entries: [] },
  { id: 'lt_voidglass_wastes', entries: [] },
  { id: 'lt_voidglass_wastes_dungeon', entries: [] },
  { id: 'lt_last_sun_plateau', entries: [] },
  { id: 'lt_last_sun_plateau_dungeon', entries: [] },
  { id: 'lt_raid_stormpeak_trial_40', entries: [] },
  { id: 'lt_raid_last_sun_vanguard_60', entries: [] },
  { id: 'lt_raid_voidglass_citadel_60', entries: [] },
  { id: 'lt_raid_worldcore_zero_60', entries: [] }
];

export const EXPANSION_MOBS: MobDefinition[] = [
  { id: 'ironwood_frontier_stalker', name: 'Следопыт: Железный Рубеж', level: 21, stats: { hp: 960, mana: 88, attack: 114, magic: 48, defense: 59, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier', tags: ['beast'] },
  { id: 'ironwood_frontier_adept', name: 'Адепт: Железный Рубеж', level: 22, stats: { hp: 796, mana: 304, attack: 110, magic: 115, defense: 56, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier', tags: ['humanoid', 'magic'] },
  { id: 'ironwood_frontier_sentinel', name: 'Страж: Железный Рубеж', level: 23, stats: { hp: 1030, mana: 94, attack: 122, magic: 52, defense: 63, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier', tags: ['humanoid', 'elite'] },
  { id: 'ironwood_frontier_wraith', name: 'Тень: Железный Рубеж', level: 24, stats: { hp: 852, mana: 328, attack: 118, magic: 123, defense: 60, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier', tags: ['spirit', 'magic'] },
  { id: 'ironwood_frontier_dungeon_guard', name: 'Гвардеец данжа: Железный Рубеж', level: 22, stats: { hp: 995, mana: 91, attack: 118, magic: 50, defense: 61, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'ironwood_frontier_dungeon_oracle', name: 'Оракул данжа: Железный Рубеж', level: 23, stats: { hp: 824, mana: 316, attack: 114, magic: 119, defense: 58, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'ironwood_frontier_dungeon_boss', name: 'Хранитель данжа: Железный Рубеж', level: 24, stats: { hp: 2761, mana: 208, attack: 136, magic: 123, defense: 72, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_ironwood_frontier_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'saltwind_coast_stalker', name: 'Следопыт: Солёный Берег', level: 25, stats: { hp: 1100, mana: 100, attack: 130, magic: 56, defense: 67, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast', tags: ['beast'] },
  { id: 'saltwind_coast_adept', name: 'Адепт: Солёный Берег', level: 26, stats: { hp: 908, mana: 352, attack: 126, magic: 131, defense: 64, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast', tags: ['humanoid', 'magic'] },
  { id: 'saltwind_coast_sentinel', name: 'Страж: Солёный Берег', level: 27, stats: { hp: 1170, mana: 106, attack: 138, magic: 60, defense: 71, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast', tags: ['humanoid', 'elite'] },
  { id: 'saltwind_coast_wraith', name: 'Тень: Солёный Берег', level: 28, stats: { hp: 964, mana: 376, attack: 134, magic: 139, defense: 68, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast', tags: ['spirit', 'magic'] },
  { id: 'saltwind_coast_dungeon_guard', name: 'Гвардеец данжа: Солёный Берег', level: 26, stats: { hp: 1135, mana: 103, attack: 134, magic: 58, defense: 69, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'saltwind_coast_dungeon_oracle', name: 'Оракул данжа: Солёный Берег', level: 27, stats: { hp: 936, mana: 364, attack: 130, magic: 135, defense: 66, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'saltwind_coast_dungeon_boss', name: 'Хранитель данжа: Солёный Берег', level: 28, stats: { hp: 3123, mana: 236, attack: 152, magic: 139, defense: 80, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_saltwind_coast_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'emberfall_badlands_stalker', name: 'Следопыт: Пеплопад', level: 29, stats: { hp: 1240, mana: 112, attack: 146, magic: 64, defense: 75, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands', tags: ['beast'] },
  { id: 'emberfall_badlands_adept', name: 'Адепт: Пеплопад', level: 30, stats: { hp: 1020, mana: 400, attack: 142, magic: 147, defense: 72, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands', tags: ['humanoid', 'magic'] },
  { id: 'emberfall_badlands_sentinel', name: 'Страж: Пеплопад', level: 31, stats: { hp: 1310, mana: 118, attack: 154, magic: 68, defense: 79, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands', tags: ['humanoid', 'elite'] },
  { id: 'emberfall_badlands_wraith', name: 'Тень: Пеплопад', level: 32, stats: { hp: 1076, mana: 424, attack: 150, magic: 155, defense: 76, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands', tags: ['spirit', 'magic'] },
  { id: 'emberfall_badlands_dungeon_guard', name: 'Гвардеец данжа: Пеплопад', level: 30, stats: { hp: 1275, mana: 115, attack: 150, magic: 66, defense: 77, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'emberfall_badlands_dungeon_oracle', name: 'Оракул данжа: Пеплопад', level: 31, stats: { hp: 1048, mana: 412, attack: 146, magic: 151, defense: 74, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'emberfall_badlands_dungeon_boss', name: 'Хранитель данжа: Пеплопад', level: 32, stats: { hp: 3487, mana: 264, attack: 168, magic: 155, defense: 88, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_emberfall_badlands_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'duskglass_reach_stalker', name: 'Следопыт: Сумрачное Стекло', level: 33, stats: { hp: 1380, mana: 124, attack: 162, magic: 72, defense: 83, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach', tags: ['beast'] },
  { id: 'duskglass_reach_adept', name: 'Адепт: Сумрачное Стекло', level: 34, stats: { hp: 1132, mana: 448, attack: 158, magic: 163, defense: 80, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach', tags: ['humanoid', 'magic'] },
  { id: 'duskglass_reach_sentinel', name: 'Страж: Сумрачное Стекло', level: 35, stats: { hp: 1450, mana: 130, attack: 170, magic: 76, defense: 87, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach', tags: ['humanoid', 'elite'] },
  { id: 'duskglass_reach_wraith', name: 'Тень: Сумрачное Стекло', level: 36, stats: { hp: 1188, mana: 472, attack: 166, magic: 171, defense: 84, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach', tags: ['spirit', 'magic'] },
  { id: 'duskglass_reach_dungeon_guard', name: 'Гвардеец данжа: Сумрачное Стекло', level: 34, stats: { hp: 1415, mana: 127, attack: 166, magic: 74, defense: 85, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'duskglass_reach_dungeon_oracle', name: 'Оракул данжа: Сумрачное Стекло', level: 35, stats: { hp: 1160, mana: 460, attack: 162, magic: 167, defense: 82, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'duskglass_reach_dungeon_boss', name: 'Хранитель данжа: Сумрачное Стекло', level: 36, stats: { hp: 3848, mana: 292, attack: 184, magic: 171, defense: 96, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_duskglass_reach_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'stormpeak_gate_stalker', name: 'Следопыт: Врата Грозового Пика', level: 37, stats: { hp: 1520, mana: 136, attack: 178, magic: 80, defense: 91, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate', tags: ['beast'] },
  { id: 'stormpeak_gate_adept', name: 'Адепт: Врата Грозового Пика', level: 38, stats: { hp: 1244, mana: 496, attack: 174, magic: 179, defense: 88, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate', tags: ['humanoid', 'magic'] },
  { id: 'stormpeak_gate_sentinel', name: 'Страж: Врата Грозового Пика', level: 39, stats: { hp: 1590, mana: 142, attack: 186, magic: 84, defense: 95, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate', tags: ['humanoid', 'elite'] },
  { id: 'stormpeak_gate_wraith', name: 'Тень: Врата Грозового Пика', level: 40, stats: { hp: 1300, mana: 520, attack: 182, magic: 187, defense: 92, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate', tags: ['spirit', 'magic'] },
  { id: 'stormpeak_gate_dungeon_guard', name: 'Гвардеец данжа: Врата Грозового Пика', level: 38, stats: { hp: 1555, mana: 139, attack: 182, magic: 82, defense: 93, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'stormpeak_gate_dungeon_oracle', name: 'Оракул данжа: Врата Грозового Пика', level: 39, stats: { hp: 1272, mana: 508, attack: 178, magic: 183, defense: 90, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'stormpeak_gate_dungeon_boss', name: 'Хранитель данжа: Врата Грозового Пика', level: 40, stats: { hp: 4212, mana: 320, attack: 200, magic: 187, defense: 104, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_stormpeak_gate_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'hollow_star_marsh_stalker', name: 'Следопыт: Трясина Пустой Звезды', level: 41, stats: { hp: 1660, mana: 148, attack: 194, magic: 88, defense: 99, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh', tags: ['beast'] },
  { id: 'hollow_star_marsh_adept', name: 'Адепт: Трясина Пустой Звезды', level: 42, stats: { hp: 1356, mana: 544, attack: 190, magic: 195, defense: 96, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh', tags: ['humanoid', 'magic'] },
  { id: 'hollow_star_marsh_sentinel', name: 'Страж: Трясина Пустой Звезды', level: 43, stats: { hp: 1730, mana: 154, attack: 202, magic: 92, defense: 103, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh', tags: ['humanoid', 'elite'] },
  { id: 'hollow_star_marsh_wraith', name: 'Тень: Трясина Пустой Звезды', level: 44, stats: { hp: 1412, mana: 568, attack: 198, magic: 203, defense: 100, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh', tags: ['spirit', 'magic'] },
  { id: 'hollow_star_marsh_dungeon_guard', name: 'Гвардеец данжа: Трясина Пустой Звезды', level: 42, stats: { hp: 1695, mana: 151, attack: 198, magic: 90, defense: 101, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'hollow_star_marsh_dungeon_oracle', name: 'Оракул данжа: Трясина Пустой Звезды', level: 43, stats: { hp: 1384, mana: 556, attack: 194, magic: 199, defense: 98, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'hollow_star_marsh_dungeon_boss', name: 'Хранитель данжа: Трясина Пустой Звезды', level: 44, stats: { hp: 4576, mana: 348, attack: 216, magic: 203, defense: 112, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_hollow_star_marsh_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'crimson_obelisk_stalker', name: 'Следопыт: Багровый Обелиск', level: 45, stats: { hp: 1800, mana: 160, attack: 210, magic: 96, defense: 107, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk', tags: ['beast'] },
  { id: 'crimson_obelisk_adept', name: 'Адепт: Багровый Обелиск', level: 46, stats: { hp: 1468, mana: 592, attack: 206, magic: 211, defense: 104, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk', tags: ['humanoid', 'magic'] },
  { id: 'crimson_obelisk_sentinel', name: 'Страж: Багровый Обелиск', level: 47, stats: { hp: 1870, mana: 166, attack: 218, magic: 100, defense: 111, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk', tags: ['humanoid', 'elite'] },
  { id: 'crimson_obelisk_wraith', name: 'Тень: Багровый Обелиск', level: 48, stats: { hp: 1524, mana: 616, attack: 214, magic: 219, defense: 108, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk', tags: ['spirit', 'magic'] },
  { id: 'crimson_obelisk_dungeon_guard', name: 'Гвардеец данжа: Багровый Обелиск', level: 46, stats: { hp: 1835, mana: 163, attack: 214, magic: 98, defense: 109, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'crimson_obelisk_dungeon_oracle', name: 'Оракул данжа: Багровый Обелиск', level: 47, stats: { hp: 1496, mana: 604, attack: 210, magic: 215, defense: 106, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'crimson_obelisk_dungeon_boss', name: 'Хранитель данжа: Багровый Обелиск', level: 48, stats: { hp: 4937, mana: 376, attack: 232, magic: 219, defense: 120, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_crimson_obelisk_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'pale_king_road_stalker', name: 'Следопыт: Дорога Бледного Короля', level: 49, stats: { hp: 1940, mana: 172, attack: 226, magic: 104, defense: 115, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road', tags: ['beast'] },
  { id: 'pale_king_road_adept', name: 'Адепт: Дорога Бледного Короля', level: 50, stats: { hp: 1580, mana: 640, attack: 222, magic: 227, defense: 112, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road', tags: ['humanoid', 'magic'] },
  { id: 'pale_king_road_sentinel', name: 'Страж: Дорога Бледного Короля', level: 51, stats: { hp: 2010, mana: 178, attack: 234, magic: 108, defense: 119, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road', tags: ['humanoid', 'elite'] },
  { id: 'pale_king_road_wraith', name: 'Тень: Дорога Бледного Короля', level: 52, stats: { hp: 1636, mana: 664, attack: 230, magic: 235, defense: 116, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road', tags: ['spirit', 'magic'] },
  { id: 'pale_king_road_dungeon_guard', name: 'Гвардеец данжа: Дорога Бледного Короля', level: 50, stats: { hp: 1975, mana: 175, attack: 230, magic: 106, defense: 117, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'pale_king_road_dungeon_oracle', name: 'Оракул данжа: Дорога Бледного Короля', level: 51, stats: { hp: 1608, mana: 652, attack: 226, magic: 231, defense: 114, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'pale_king_road_dungeon_boss', name: 'Хранитель данжа: Дорога Бледного Короля', level: 52, stats: { hp: 5301, mana: 404, attack: 248, magic: 235, defense: 128, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_pale_king_road_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'voidglass_wastes_stalker', name: 'Следопыт: Пустоши Чёрного Стекла', level: 53, stats: { hp: 2080, mana: 184, attack: 242, magic: 112, defense: 123, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes', tags: ['beast'] },
  { id: 'voidglass_wastes_adept', name: 'Адепт: Пустоши Чёрного Стекла', level: 54, stats: { hp: 1692, mana: 688, attack: 238, magic: 243, defense: 120, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes', tags: ['humanoid', 'magic'] },
  { id: 'voidglass_wastes_sentinel', name: 'Страж: Пустоши Чёрного Стекла', level: 55, stats: { hp: 2150, mana: 190, attack: 250, magic: 116, defense: 127, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes', tags: ['humanoid', 'elite'] },
  { id: 'voidglass_wastes_wraith', name: 'Тень: Пустоши Чёрного Стекла', level: 56, stats: { hp: 1748, mana: 712, attack: 246, magic: 251, defense: 124, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes', tags: ['spirit', 'magic'] },
  { id: 'voidglass_wastes_dungeon_guard', name: 'Гвардеец данжа: Пустоши Чёрного Стекла', level: 54, stats: { hp: 2115, mana: 187, attack: 246, magic: 114, defense: 125, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'voidglass_wastes_dungeon_oracle', name: 'Оракул данжа: Пустоши Чёрного Стекла', level: 55, stats: { hp: 1720, mana: 700, attack: 242, magic: 247, defense: 122, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'voidglass_wastes_dungeon_boss', name: 'Хранитель данжа: Пустоши Чёрного Стекла', level: 56, stats: { hp: 5663, mana: 432, attack: 264, magic: 251, defense: 136, speed: 7 }, xp: 1, gold: [1, 1], lootTableId: 'lt_voidglass_wastes_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'last_sun_plateau_stalker', name: 'Следопыт: Плато Последнего Солнца', level: 57, stats: { hp: 2220, mana: 196, attack: 258, magic: 120, defense: 131, speed: 8 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau', tags: ['beast'] },
  { id: 'last_sun_plateau_adept', name: 'Адепт: Плато Последнего Солнца', level: 58, stats: { hp: 1804, mana: 736, attack: 254, magic: 259, defense: 128, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau', tags: ['humanoid', 'magic'] },
  { id: 'last_sun_plateau_sentinel', name: 'Страж: Плато Последнего Солнца', level: 59, stats: { hp: 2290, mana: 202, attack: 266, magic: 124, defense: 135, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau', tags: ['humanoid', 'elite'] },
  { id: 'last_sun_plateau_wraith', name: 'Тень: Плато Последнего Солнца', level: 60, stats: { hp: 1860, mana: 760, attack: 262, magic: 267, defense: 132, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau', tags: ['spirit', 'magic'] },
  { id: 'last_sun_plateau_dungeon_guard', name: 'Гвардеец данжа: Плато Последнего Солнца', level: 58, stats: { hp: 2255, mana: 199, attack: 262, magic: 122, defense: 133, speed: 9 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau_dungeon', tags: ['humanoid', 'dungeon'] },
  { id: 'last_sun_plateau_dungeon_oracle', name: 'Оракул данжа: Плато Последнего Солнца', level: 59, stats: { hp: 1832, mana: 748, attack: 258, magic: 263, defense: 130, speed: 10 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau_dungeon', tags: ['magic', 'dungeon'] },
  { id: 'last_sun_plateau_dungeon_boss', name: 'Хранитель данжа: Плато Последнего Солнца', level: 60, stats: { hp: 6026, mana: 460, attack: 280, magic: 267, defense: 144, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_last_sun_plateau_dungeon', tags: ['boss', 'dungeon', 'aoe'] },
  { id: 'stormpeak_trial_40_raider', name: 'Рейдовый страж: Испытание Грозового Пика', level: 40, stats: { hp: 2600, mana: 145, attack: 190, magic: 86, defense: 97, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_stormpeak_trial_40', tags: ['humanoid', 'raid'] },
  { id: 'stormpeak_trial_40_oracle', name: 'Рейдовый оракул: Испытание Грозового Пика', level: 40, stats: { hp: 2080, mana: 520, attack: 182, magic: 187, defense: 92, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_stormpeak_trial_40', tags: ['magic', 'raid'] },
  { id: 'stormpeak_trial_40_boss', name: 'Босс: Испытание Грозового Пика', level: 40, stats: { hp: 6739, mana: 320, attack: 200, magic: 187, defense: 104, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_stormpeak_trial_40', tags: ['boss', 'raid', 'aoe'] },
  { id: 'last_sun_vanguard_60_raider', name: 'Рейдовый страж: Авангард Последнего Солнца', level: 60, stats: { hp: 3720, mana: 205, attack: 270, magic: 126, defense: 137, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_last_sun_vanguard_60', tags: ['humanoid', 'raid'] },
  { id: 'last_sun_vanguard_60_oracle', name: 'Рейдовый оракул: Авангард Последнего Солнца', level: 60, stats: { hp: 2976, mana: 760, attack: 262, magic: 267, defense: 132, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_last_sun_vanguard_60', tags: ['magic', 'raid'] },
  { id: 'last_sun_vanguard_60_boss', name: 'Босс: Авангард Последнего Солнца', level: 60, stats: { hp: 9643, mana: 460, attack: 280, magic: 267, defense: 144, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_last_sun_vanguard_60', tags: ['boss', 'raid', 'aoe'] },
  { id: 'voidglass_citadel_60_raider', name: 'Рейдовый страж: Цитадель Чёрного Стекла', level: 60, stats: { hp: 3720, mana: 205, attack: 270, magic: 126, defense: 137, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_voidglass_citadel_60', tags: ['humanoid', 'raid'] },
  { id: 'voidglass_citadel_60_oracle', name: 'Рейдовый оракул: Цитадель Чёрного Стекла', level: 60, stats: { hp: 2976, mana: 760, attack: 262, magic: 267, defense: 132, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_voidglass_citadel_60', tags: ['magic', 'raid'] },
  { id: 'voidglass_citadel_60_boss', name: 'Босс: Цитадель Чёрного Стекла', level: 60, stats: { hp: 9643, mana: 460, attack: 280, magic: 267, defense: 144, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_voidglass_citadel_60', tags: ['boss', 'raid', 'aoe'] },
  { id: 'worldcore_zero_60_raider', name: 'Рейдовый страж: Нулевое Сердце Мира', level: 60, stats: { hp: 3720, mana: 205, attack: 270, magic: 126, defense: 137, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_worldcore_zero_60', tags: ['humanoid', 'raid'] },
  { id: 'worldcore_zero_60_oracle', name: 'Рейдовый оракул: Нулевое Сердце Мира', level: 60, stats: { hp: 2976, mana: 760, attack: 262, magic: 267, defense: 132, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_worldcore_zero_60', tags: ['magic', 'raid'] },
  { id: 'worldcore_zero_60_boss', name: 'Босс: Нулевое Сердце Мира', level: 60, stats: { hp: 9643, mana: 460, attack: 280, magic: 267, defense: 144, speed: 6 }, xp: 1, gold: [1, 1], lootTableId: 'lt_raid_worldcore_zero_60', tags: ['boss', 'raid', 'aoe'] }
];

export const EXPANSION_SPOTS: SpotDefinition[] = [
  { id: 'ironwood_frontier_outer', zoneId: 'ironwood_frontier', name: 'Железный Рубеж: внешний участок', levelRange: [21, 22], mobIds: ['ironwood_frontier_stalker', 'ironwood_frontier_adept'], timeCostMinutes: 203, risk: 7, tags: ['solo', 'expansion'] },
  { id: 'ironwood_frontier_deep', zoneId: 'ironwood_frontier', name: 'Железный Рубеж: глубокий участок', levelRange: [23, 24], mobIds: ['ironwood_frontier_sentinel', 'ironwood_frontier_wraith'], timeCostMinutes: 227, risk: 8, tags: ['elite', 'expansion'] },
  { id: 'saltwind_coast_outer', zoneId: 'saltwind_coast', name: 'Солёный Берег: внешний участок', levelRange: [25, 26], mobIds: ['saltwind_coast_stalker', 'saltwind_coast_adept'], timeCostMinutes: 215, risk: 7, tags: ['solo', 'expansion'] },
  { id: 'saltwind_coast_deep', zoneId: 'saltwind_coast', name: 'Солёный Берег: глубокий участок', levelRange: [27, 28], mobIds: ['saltwind_coast_sentinel', 'saltwind_coast_wraith'], timeCostMinutes: 239, risk: 8, tags: ['elite', 'expansion'] },
  { id: 'emberfall_badlands_outer', zoneId: 'emberfall_badlands', name: 'Пеплопад: внешний участок', levelRange: [29, 30], mobIds: ['emberfall_badlands_stalker', 'emberfall_badlands_adept'], timeCostMinutes: 227, risk: 7, tags: ['solo', 'expansion'] },
  { id: 'emberfall_badlands_deep', zoneId: 'emberfall_badlands', name: 'Пеплопад: глубокий участок', levelRange: [31, 32], mobIds: ['emberfall_badlands_sentinel', 'emberfall_badlands_wraith'], timeCostMinutes: 251, risk: 9, tags: ['elite', 'expansion'] },
  { id: 'duskglass_reach_outer', zoneId: 'duskglass_reach', name: 'Сумрачное Стекло: внешний участок', levelRange: [33, 34], mobIds: ['duskglass_reach_stalker', 'duskglass_reach_adept'], timeCostMinutes: 239, risk: 8, tags: ['solo', 'expansion'] },
  { id: 'duskglass_reach_deep', zoneId: 'duskglass_reach', name: 'Сумрачное Стекло: глубокий участок', levelRange: [35, 36], mobIds: ['duskglass_reach_sentinel', 'duskglass_reach_wraith'], timeCostMinutes: 263, risk: 9, tags: ['elite', 'expansion'] },
  { id: 'stormpeak_gate_outer', zoneId: 'stormpeak_gate', name: 'Врата Грозового Пика: внешний участок', levelRange: [37, 38], mobIds: ['stormpeak_gate_stalker', 'stormpeak_gate_adept'], timeCostMinutes: 251, risk: 8, tags: ['solo', 'expansion'] },
  { id: 'stormpeak_gate_deep', zoneId: 'stormpeak_gate', name: 'Врата Грозового Пика: глубокий участок', levelRange: [39, 40], mobIds: ['stormpeak_gate_sentinel', 'stormpeak_gate_wraith'], timeCostMinutes: 275, risk: 10, tags: ['elite', 'expansion'] },
  { id: 'hollow_star_marsh_outer', zoneId: 'hollow_star_marsh', name: 'Трясина Пустой Звезды: внешний участок', levelRange: [41, 42], mobIds: ['hollow_star_marsh_stalker', 'hollow_star_marsh_adept'], timeCostMinutes: 263, risk: 9, tags: ['solo', 'expansion'] },
  { id: 'hollow_star_marsh_deep', zoneId: 'hollow_star_marsh', name: 'Трясина Пустой Звезды: глубокий участок', levelRange: [43, 44], mobIds: ['hollow_star_marsh_sentinel', 'hollow_star_marsh_wraith'], timeCostMinutes: 287, risk: 10, tags: ['elite', 'expansion'] },
  { id: 'crimson_obelisk_outer', zoneId: 'crimson_obelisk', name: 'Багровый Обелиск: внешний участок', levelRange: [45, 46], mobIds: ['crimson_obelisk_stalker', 'crimson_obelisk_adept'], timeCostMinutes: 275, risk: 9, tags: ['solo', 'expansion'] },
  { id: 'crimson_obelisk_deep', zoneId: 'crimson_obelisk', name: 'Багровый Обелиск: глубокий участок', levelRange: [47, 48], mobIds: ['crimson_obelisk_sentinel', 'crimson_obelisk_wraith'], timeCostMinutes: 299, risk: 10, tags: ['elite', 'expansion'] },
  { id: 'pale_king_road_outer', zoneId: 'pale_king_road', name: 'Дорога Бледного Короля: внешний участок', levelRange: [49, 50], mobIds: ['pale_king_road_stalker', 'pale_king_road_adept'], timeCostMinutes: 287, risk: 9, tags: ['solo', 'expansion'] },
  { id: 'pale_king_road_deep', zoneId: 'pale_king_road', name: 'Дорога Бледного Короля: глубокий участок', levelRange: [51, 52], mobIds: ['pale_king_road_sentinel', 'pale_king_road_wraith'], timeCostMinutes: 311, risk: 10, tags: ['elite', 'expansion'] },
  { id: 'voidglass_wastes_outer', zoneId: 'voidglass_wastes', name: 'Пустоши Чёрного Стекла: внешний участок', levelRange: [53, 54], mobIds: ['voidglass_wastes_stalker', 'voidglass_wastes_adept'], timeCostMinutes: 299, risk: 10, tags: ['solo', 'expansion'] },
  { id: 'voidglass_wastes_deep', zoneId: 'voidglass_wastes', name: 'Пустоши Чёрного Стекла: глубокий участок', levelRange: [55, 56], mobIds: ['voidglass_wastes_sentinel', 'voidglass_wastes_wraith'], timeCostMinutes: 323, risk: 10, tags: ['elite', 'expansion'] },
  { id: 'last_sun_plateau_outer', zoneId: 'last_sun_plateau', name: 'Плато Последнего Солнца: внешний участок', levelRange: [57, 58], mobIds: ['last_sun_plateau_stalker', 'last_sun_plateau_adept'], timeCostMinutes: 311, risk: 10, tags: ['solo', 'expansion'] },
  { id: 'last_sun_plateau_deep', zoneId: 'last_sun_plateau', name: 'Плато Последнего Солнца: глубокий участок', levelRange: [59, 60], mobIds: ['last_sun_plateau_sentinel', 'last_sun_plateau_wraith'], timeCostMinutes: 335, risk: 10, tags: ['elite', 'expansion'] }
];

export const EXPANSION_ZONES: ZoneDefinition[] = [
  { id: 'ironwood_frontier', name: 'Железный Рубеж', levelRange: [21, 24], description: 'Lv. 21–24', spotIds: ['ironwood_frontier_outer', 'ironwood_frontier_deep'] },
  { id: 'saltwind_coast', name: 'Солёный Берег', levelRange: [25, 28], description: 'Lv. 25–28', spotIds: ['saltwind_coast_outer', 'saltwind_coast_deep'] },
  { id: 'emberfall_badlands', name: 'Пеплопад', levelRange: [29, 32], description: 'Lv. 29–32', spotIds: ['emberfall_badlands_outer', 'emberfall_badlands_deep'] },
  { id: 'duskglass_reach', name: 'Сумрачное Стекло', levelRange: [33, 36], description: 'Lv. 33–36', spotIds: ['duskglass_reach_outer', 'duskglass_reach_deep'] },
  { id: 'stormpeak_gate', name: 'Врата Грозового Пика', levelRange: [37, 40], description: 'Lv. 37–40', spotIds: ['stormpeak_gate_outer', 'stormpeak_gate_deep'] },
  { id: 'hollow_star_marsh', name: 'Трясина Пустой Звезды', levelRange: [41, 44], description: 'Lv. 41–44', spotIds: ['hollow_star_marsh_outer', 'hollow_star_marsh_deep'] },
  { id: 'crimson_obelisk', name: 'Багровый Обелиск', levelRange: [45, 48], description: 'Lv. 45–48', spotIds: ['crimson_obelisk_outer', 'crimson_obelisk_deep'] },
  { id: 'pale_king_road', name: 'Дорога Бледного Короля', levelRange: [49, 52], description: 'Lv. 49–52', spotIds: ['pale_king_road_outer', 'pale_king_road_deep'] },
  { id: 'voidglass_wastes', name: 'Пустоши Чёрного Стекла', levelRange: [53, 56], description: 'Lv. 53–56', spotIds: ['voidglass_wastes_outer', 'voidglass_wastes_deep'] },
  { id: 'last_sun_plateau', name: 'Плато Последнего Солнца', levelRange: [57, 60], description: 'Lv. 57–60', spotIds: ['last_sun_plateau_outer', 'last_sun_plateau_deep'] }
];

export const EXPANSION_DUNGEONS: DungeonDefinition[] = [
  { id: 'ironwood_frontier_dungeon', zoneId: 'ironwood_frontier', name: 'Данж: Железный Рубеж', levelRange: [21, 24], partySize: 5, timeCostMinutes: 444, contentType: 'dungeon', bossMobId: 'ironwood_frontier_dungeon_boss', lootTableId: 'lt_ironwood_frontier_dungeon', description: 'Lv. 21–24 · пати 5', floors: [
    { id: 'ironwood_frontier_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['ironwood_frontier_dungeon_guard', 'ironwood_frontier_stalker'], timeCostMinutes: 55 },
    { id: 'ironwood_frontier_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['ironwood_frontier_dungeon_guard', 'ironwood_frontier_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'ironwood_frontier_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['ironwood_frontier_dungeon_guard', 'ironwood_frontier_dungeon_oracle', 'ironwood_frontier_sentinel'], timeCostMinutes: 65 },
    { id: 'ironwood_frontier_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['ironwood_frontier_dungeon_oracle', 'ironwood_frontier_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'saltwind_coast_dungeon', zoneId: 'saltwind_coast', name: 'Данж: Солёный Берег', levelRange: [25, 28], partySize: 5, timeCostMinutes: 460, contentType: 'dungeon', bossMobId: 'saltwind_coast_dungeon_boss', lootTableId: 'lt_saltwind_coast_dungeon', description: 'Lv. 25–28 · пати 5', floors: [
    { id: 'saltwind_coast_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['saltwind_coast_dungeon_guard', 'saltwind_coast_stalker'], timeCostMinutes: 55 },
    { id: 'saltwind_coast_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['saltwind_coast_dungeon_guard', 'saltwind_coast_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'saltwind_coast_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['saltwind_coast_dungeon_guard', 'saltwind_coast_dungeon_oracle', 'saltwind_coast_sentinel'], timeCostMinutes: 65 },
    { id: 'saltwind_coast_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['saltwind_coast_dungeon_oracle', 'saltwind_coast_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'emberfall_badlands_dungeon', zoneId: 'emberfall_badlands', name: 'Данж: Пеплопад', levelRange: [29, 32], partySize: 5, timeCostMinutes: 476, contentType: 'dungeon', bossMobId: 'emberfall_badlands_dungeon_boss', lootTableId: 'lt_emberfall_badlands_dungeon', description: 'Lv. 29–32 · пати 5', floors: [
    { id: 'emberfall_badlands_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['emberfall_badlands_dungeon_guard', 'emberfall_badlands_stalker'], timeCostMinutes: 55 },
    { id: 'emberfall_badlands_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['emberfall_badlands_dungeon_guard', 'emberfall_badlands_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'emberfall_badlands_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['emberfall_badlands_dungeon_guard', 'emberfall_badlands_dungeon_oracle', 'emberfall_badlands_sentinel'], timeCostMinutes: 65 },
    { id: 'emberfall_badlands_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['emberfall_badlands_dungeon_oracle', 'emberfall_badlands_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'duskglass_reach_dungeon', zoneId: 'duskglass_reach', name: 'Данж: Сумрачное Стекло', levelRange: [33, 36], partySize: 5, timeCostMinutes: 492, contentType: 'dungeon', bossMobId: 'duskglass_reach_dungeon_boss', lootTableId: 'lt_duskglass_reach_dungeon', description: 'Lv. 33–36 · пати 5', floors: [
    { id: 'duskglass_reach_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['duskglass_reach_dungeon_guard', 'duskglass_reach_stalker'], timeCostMinutes: 55 },
    { id: 'duskglass_reach_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['duskglass_reach_dungeon_guard', 'duskglass_reach_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'duskglass_reach_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['duskglass_reach_dungeon_guard', 'duskglass_reach_dungeon_oracle', 'duskglass_reach_sentinel'], timeCostMinutes: 65 },
    { id: 'duskglass_reach_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['duskglass_reach_dungeon_oracle', 'duskglass_reach_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'stormpeak_gate_dungeon', zoneId: 'stormpeak_gate', name: 'Данж: Врата Грозового Пика', levelRange: [37, 40], partySize: 5, timeCostMinutes: 508, contentType: 'dungeon', bossMobId: 'stormpeak_gate_dungeon_boss', lootTableId: 'lt_stormpeak_gate_dungeon', description: 'Lv. 37–40 · пати 5', floors: [
    { id: 'stormpeak_gate_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['stormpeak_gate_dungeon_guard', 'stormpeak_gate_stalker'], timeCostMinutes: 55 },
    { id: 'stormpeak_gate_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['stormpeak_gate_dungeon_guard', 'stormpeak_gate_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'stormpeak_gate_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['stormpeak_gate_dungeon_guard', 'stormpeak_gate_dungeon_oracle', 'stormpeak_gate_sentinel'], timeCostMinutes: 65 },
    { id: 'stormpeak_gate_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['stormpeak_gate_dungeon_oracle', 'stormpeak_gate_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'hollow_star_marsh_dungeon', zoneId: 'hollow_star_marsh', name: 'Данж: Трясина Пустой Звезды', levelRange: [41, 44], partySize: 5, timeCostMinutes: 524, contentType: 'dungeon', bossMobId: 'hollow_star_marsh_dungeon_boss', lootTableId: 'lt_hollow_star_marsh_dungeon', description: 'Lv. 41–44 · пати 5', floors: [
    { id: 'hollow_star_marsh_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['hollow_star_marsh_dungeon_guard', 'hollow_star_marsh_stalker'], timeCostMinutes: 55 },
    { id: 'hollow_star_marsh_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['hollow_star_marsh_dungeon_guard', 'hollow_star_marsh_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'hollow_star_marsh_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['hollow_star_marsh_dungeon_guard', 'hollow_star_marsh_dungeon_oracle', 'hollow_star_marsh_sentinel'], timeCostMinutes: 65 },
    { id: 'hollow_star_marsh_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['hollow_star_marsh_dungeon_oracle', 'hollow_star_marsh_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'crimson_obelisk_dungeon', zoneId: 'crimson_obelisk', name: 'Данж: Багровый Обелиск', levelRange: [45, 48], partySize: 5, timeCostMinutes: 540, contentType: 'dungeon', bossMobId: 'crimson_obelisk_dungeon_boss', lootTableId: 'lt_crimson_obelisk_dungeon', description: 'Lv. 45–48 · пати 5', floors: [
    { id: 'crimson_obelisk_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['crimson_obelisk_dungeon_guard', 'crimson_obelisk_stalker'], timeCostMinutes: 55 },
    { id: 'crimson_obelisk_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['crimson_obelisk_dungeon_guard', 'crimson_obelisk_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'crimson_obelisk_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['crimson_obelisk_dungeon_guard', 'crimson_obelisk_dungeon_oracle', 'crimson_obelisk_sentinel'], timeCostMinutes: 65 },
    { id: 'crimson_obelisk_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['crimson_obelisk_dungeon_oracle', 'crimson_obelisk_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'pale_king_road_dungeon', zoneId: 'pale_king_road', name: 'Данж: Дорога Бледного Короля', levelRange: [49, 52], partySize: 5, timeCostMinutes: 556, contentType: 'dungeon', bossMobId: 'pale_king_road_dungeon_boss', lootTableId: 'lt_pale_king_road_dungeon', description: 'Lv. 49–52 · пати 5', floors: [
    { id: 'pale_king_road_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['pale_king_road_dungeon_guard', 'pale_king_road_stalker'], timeCostMinutes: 55 },
    { id: 'pale_king_road_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['pale_king_road_dungeon_guard', 'pale_king_road_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'pale_king_road_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['pale_king_road_dungeon_guard', 'pale_king_road_dungeon_oracle', 'pale_king_road_sentinel'], timeCostMinutes: 65 },
    { id: 'pale_king_road_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['pale_king_road_dungeon_oracle', 'pale_king_road_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'voidglass_wastes_dungeon', zoneId: 'voidglass_wastes', name: 'Данж: Пустоши Чёрного Стекла', levelRange: [53, 56], partySize: 5, timeCostMinutes: 572, contentType: 'dungeon', bossMobId: 'voidglass_wastes_dungeon_boss', lootTableId: 'lt_voidglass_wastes_dungeon', description: 'Lv. 53–56 · пати 5', floors: [
    { id: 'voidglass_wastes_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['voidglass_wastes_dungeon_guard', 'voidglass_wastes_stalker'], timeCostMinutes: 55 },
    { id: 'voidglass_wastes_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['voidglass_wastes_dungeon_guard', 'voidglass_wastes_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'voidglass_wastes_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['voidglass_wastes_dungeon_guard', 'voidglass_wastes_dungeon_oracle', 'voidglass_wastes_sentinel'], timeCostMinutes: 65 },
    { id: 'voidglass_wastes_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['voidglass_wastes_dungeon_oracle', 'voidglass_wastes_dungeon_boss'], timeCostMinutes: 95 }
  ] },
  { id: 'last_sun_plateau_dungeon', zoneId: 'last_sun_plateau', name: 'Данж: Плато Последнего Солнца', levelRange: [57, 60], partySize: 5, timeCostMinutes: 588, contentType: 'dungeon', bossMobId: 'last_sun_plateau_dungeon_boss', lootTableId: 'lt_last_sun_plateau_dungeon', description: 'Lv. 57–60 · пати 5', floors: [
    { id: 'last_sun_plateau_dungeon_f1', name: 'Вход', type: 'mobs', mobIds: ['last_sun_plateau_dungeon_guard', 'last_sun_plateau_stalker'], timeCostMinutes: 55 },
    { id: 'last_sun_plateau_dungeon_f2', name: 'Первый узел', type: 'boss', mobIds: ['last_sun_plateau_dungeon_guard', 'last_sun_plateau_dungeon_oracle'], timeCostMinutes: 75 },
    { id: 'last_sun_plateau_dungeon_f3', name: 'Глубина', type: 'mobs', mobIds: ['last_sun_plateau_dungeon_guard', 'last_sun_plateau_dungeon_oracle', 'last_sun_plateau_sentinel'], timeCostMinutes: 65 },
    { id: 'last_sun_plateau_dungeon_f4', name: 'Сердце', type: 'boss', mobIds: ['last_sun_plateau_dungeon_oracle', 'last_sun_plateau_dungeon_boss'], timeCostMinutes: 95 }
  ] }];

export const EXPANSION_RAIDS: DungeonDefinition[] = [
  { id: 'raid_stormpeak_trial_40', zoneId: 'stormpeak_gate', name: 'Рейд: Испытание Грозового Пика', levelRange: [40, 40], partySize: 10, timeCostMinutes: 520, contentType: 'raid', bossMobId: 'stormpeak_trial_40_boss', lootTableId: 'lt_raid_stormpeak_trial_40', description: 'Lv. 40 · рейд 10 · GS 8200', floors: [
    { id: 'stormpeak_trial_40_r1', name: 'Входной бой', type: 'mobs', mobIds: ['stormpeak_trial_40_raider', 'stormpeak_trial_40_oracle'], timeCostMinutes: 70 },
    { id: 'stormpeak_trial_40_r2', name: 'Командир', type: 'boss', mobIds: ['stormpeak_trial_40_raider', 'stormpeak_trial_40_oracle'], timeCostMinutes: 90 },
    { id: 'stormpeak_trial_40_r3', name: 'Финальная арена', type: 'boss', mobIds: ['stormpeak_trial_40_oracle', 'stormpeak_trial_40_boss'], timeCostMinutes: 130 }
  ] },
  { id: 'raid_last_sun_vanguard_60', zoneId: 'last_sun_plateau', name: 'Рейд: Авангард Последнего Солнца', levelRange: [60, 60], partySize: 10, timeCostMinutes: 720, contentType: 'raid', bossMobId: 'last_sun_vanguard_60_boss', lootTableId: 'lt_raid_last_sun_vanguard_60', description: 'Lv. 60 · рейд 10 · GS 10500', floors: [
    { id: 'last_sun_vanguard_60_r1', name: 'Входной бой', type: 'mobs', mobIds: ['last_sun_vanguard_60_raider', 'last_sun_vanguard_60_oracle'], timeCostMinutes: 70 },
    { id: 'last_sun_vanguard_60_r2', name: 'Командир', type: 'boss', mobIds: ['last_sun_vanguard_60_raider', 'last_sun_vanguard_60_oracle'], timeCostMinutes: 90 },
    { id: 'last_sun_vanguard_60_r3', name: 'Финальная арена', type: 'boss', mobIds: ['last_sun_vanguard_60_oracle', 'last_sun_vanguard_60_boss'], timeCostMinutes: 130 }
  ] },
  { id: 'raid_voidglass_citadel_60', zoneId: 'last_sun_plateau', name: 'Рейд: Цитадель Чёрного Стекла', levelRange: [60, 60], partySize: 10, timeCostMinutes: 720, contentType: 'raid', bossMobId: 'voidglass_citadel_60_boss', lootTableId: 'lt_raid_voidglass_citadel_60', description: 'Lv. 60 · рейд 10 · GS 12500', floors: [
    { id: 'voidglass_citadel_60_r1', name: 'Входной бой', type: 'mobs', mobIds: ['voidglass_citadel_60_raider', 'voidglass_citadel_60_oracle'], timeCostMinutes: 70 },
    { id: 'voidglass_citadel_60_r2', name: 'Командир', type: 'boss', mobIds: ['voidglass_citadel_60_raider', 'voidglass_citadel_60_oracle'], timeCostMinutes: 90 },
    { id: 'voidglass_citadel_60_r3', name: 'Финальная арена', type: 'boss', mobIds: ['voidglass_citadel_60_oracle', 'voidglass_citadel_60_boss'], timeCostMinutes: 130 }
  ] },
  { id: 'raid_worldcore_zero_60', zoneId: 'last_sun_plateau', name: 'Рейд: Нулевое Сердце Мира', levelRange: [60, 60], partySize: 10, timeCostMinutes: 720, contentType: 'raid', bossMobId: 'worldcore_zero_60_boss', lootTableId: 'lt_raid_worldcore_zero_60', description: 'Lv. 60 · рейд 10 · GS 14500', floors: [
    { id: 'worldcore_zero_60_r1', name: 'Входной бой', type: 'mobs', mobIds: ['worldcore_zero_60_raider', 'worldcore_zero_60_oracle'], timeCostMinutes: 70 },
    { id: 'worldcore_zero_60_r2', name: 'Командир', type: 'boss', mobIds: ['worldcore_zero_60_raider', 'worldcore_zero_60_oracle'], timeCostMinutes: 90 },
    { id: 'worldcore_zero_60_r3', name: 'Финальная арена', type: 'boss', mobIds: ['worldcore_zero_60_oracle', 'worldcore_zero_60_boss'], timeCostMinutes: 130 }
  ] }];

export const EXPANSION_QUEST_GIVERS: QuestGiverDefinition[] = [
  {
    id: 'qg_ironwood_frontier',
    name: 'Харт Роу',
    type: 'quest_giver',
    zoneId: 'ironwood_frontier',
    locationText: 'Железный Рубеж',
    levelRange: [21, 24],
    shortText: 'Железный Рубеж',
    questIds: ['quest_ironwood_frontier_cleanup', 'quest_ironwood_frontier_dungeon'],
  },
  {
    id: 'qg_saltwind_coast',
    name: 'Мира Сольвей',
    type: 'quest_giver',
    zoneId: 'saltwind_coast',
    locationText: 'Солёный Берег',
    levelRange: [25, 28],
    shortText: 'Солёный Берег',
    questIds: ['quest_saltwind_coast_cleanup', 'quest_saltwind_coast_dungeon'],
  },
  {
    id: 'qg_emberfall_badlands',
    name: 'Дорн Крейг',
    type: 'quest_giver',
    zoneId: 'emberfall_badlands',
    locationText: 'Пеплопад',
    levelRange: [29, 32],
    shortText: 'Пеплопад',
    questIds: ['quest_emberfall_badlands_cleanup', 'quest_emberfall_badlands_dungeon'],
  },
  {
    id: 'qg_duskglass_reach',
    name: 'Эйра Вейл',
    type: 'quest_giver',
    zoneId: 'duskglass_reach',
    locationText: 'Сумрачное Стекло',
    levelRange: [33, 36],
    shortText: 'Сумрачное Стекло',
    questIds: ['quest_duskglass_reach_cleanup', 'quest_duskglass_reach_dungeon'],
  },
  {
    id: 'qg_stormpeak_gate',
    name: 'Бранн Октав',
    type: 'quest_giver',
    zoneId: 'stormpeak_gate',
    locationText: 'Врата Грозового Пика',
    levelRange: [37, 40],
    shortText: 'Врата Грозового Пика',
    questIds: ['quest_stormpeak_gate_cleanup', 'quest_stormpeak_gate_dungeon', 'quest_raid_stormpeak_trial_40'],
  },
  {
    id: 'qg_hollow_star_marsh',
    name: 'Нейра Мотт',
    type: 'quest_giver',
    zoneId: 'hollow_star_marsh',
    locationText: 'Трясина Пустой Звезды',
    levelRange: [41, 44],
    shortText: 'Трясина Пустой Звезды',
    questIds: ['quest_hollow_star_marsh_cleanup', 'quest_hollow_star_marsh_dungeon'],
  },
  {
    id: 'qg_crimson_obelisk',
    name: 'Калеб Рин',
    type: 'quest_giver',
    zoneId: 'crimson_obelisk',
    locationText: 'Багровый Обелиск',
    levelRange: [45, 48],
    shortText: 'Багровый Обелиск',
    questIds: ['quest_crimson_obelisk_cleanup', 'quest_crimson_obelisk_dungeon'],
  },
  {
    id: 'qg_pale_king_road',
    name: 'Северин Холт',
    type: 'quest_giver',
    zoneId: 'pale_king_road',
    locationText: 'Дорога Бледного Короля',
    levelRange: [49, 52],
    shortText: 'Дорога Бледного Короля',
    questIds: ['quest_pale_king_road_cleanup', 'quest_pale_king_road_dungeon'],
  },
  {
    id: 'qg_voidglass_wastes',
    name: 'Лисса Ворд',
    type: 'quest_giver',
    zoneId: 'voidglass_wastes',
    locationText: 'Пустоши Чёрного Стекла',
    levelRange: [53, 56],
    shortText: 'Пустоши Чёрного Стекла',
    questIds: ['quest_voidglass_wastes_cleanup', 'quest_voidglass_wastes_dungeon'],
  },
  {
    id: 'qg_last_sun_plateau',
    name: 'Рейна Сол',
    type: 'quest_giver',
    zoneId: 'last_sun_plateau',
    locationText: 'Плато Последнего Солнца',
    levelRange: [57, 60],
    shortText: 'Плато Последнего Солнца',
    questIds: ['quest_last_sun_plateau_cleanup', 'quest_last_sun_plateau_dungeon', 'quest_raid_last_sun_vanguard_60', 'quest_raid_voidglass_citadel_60', 'quest_raid_worldcore_zero_60'],
  }
];

export const EXPANSION_QUESTS: QuestDefinition[] = [
  {
    id: 'quest_ironwood_frontier_cleanup',
    title: 'Железный Рубеж: зачистка',
    giverId: 'qg_ironwood_frontier',
    levelReq: 21,
    zoneId: 'ironwood_frontier',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['ironwood_frontier_stalker', 'ironwood_frontier_adept', 'ironwood_frontier_sentinel', 'ironwood_frontier_wraith'], required: 12 }],
    reward: { xp: 2520, gold: 735 },
    introText: 'Цель: убить 12 врагов в зоне Железный Рубеж.',
    progressText: 'Убей 12 врагов в зоне Железный Рубеж.',
    completeText: 'Зачистка зоны Железный Рубеж завершена.',
  },
  {
    id: 'quest_ironwood_frontier_dungeon',
    title: 'Данж: Железный Рубеж',
    giverId: 'qg_ironwood_frontier',
    levelReq: 21,
    zoneId: 'ironwood_frontier',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'ironwood_frontier_dungeon', required: 1 }],
    reward: { xp: 3780, gold: 1155 },
    introText: 'Цель: пройти данж зоны Железный Рубеж.',
    progressText: 'Пройди данж зоны Железный Рубеж.',
    completeText: 'Данж зоны Железный Рубеж пройден.',
  },
  {
    id: 'quest_saltwind_coast_cleanup',
    title: 'Солёный Берег: зачистка',
    giverId: 'qg_saltwind_coast',
    levelReq: 25,
    zoneId: 'saltwind_coast',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['saltwind_coast_stalker', 'saltwind_coast_adept', 'saltwind_coast_sentinel', 'saltwind_coast_wraith'], required: 12 }],
    reward: { xp: 3000, gold: 875 },
    introText: 'Цель: убить 12 врагов в зоне Солёный Берег.',
    progressText: 'Убей 12 врагов в зоне Солёный Берег.',
    completeText: 'Зачистка зоны Солёный Берег завершена.',
  },
  {
    id: 'quest_saltwind_coast_dungeon',
    title: 'Данж: Солёный Берег',
    giverId: 'qg_saltwind_coast',
    levelReq: 25,
    zoneId: 'saltwind_coast',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'saltwind_coast_dungeon', required: 1 }],
    reward: { xp: 4500, gold: 1375 },
    introText: 'Цель: пройти данж зоны Солёный Берег.',
    progressText: 'Пройди данж зоны Солёный Берег.',
    completeText: 'Данж зоны Солёный Берег пройден.',
  },
  {
    id: 'quest_emberfall_badlands_cleanup',
    title: 'Пеплопад: зачистка',
    giverId: 'qg_emberfall_badlands',
    levelReq: 29,
    zoneId: 'emberfall_badlands',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['emberfall_badlands_stalker', 'emberfall_badlands_adept', 'emberfall_badlands_sentinel', 'emberfall_badlands_wraith'], required: 12 }],
    reward: { xp: 3480, gold: 1015 },
    introText: 'Цель: убить 12 врагов в зоне Пеплопад.',
    progressText: 'Убей 12 врагов в зоне Пеплопад.',
    completeText: 'Зачистка зоны Пеплопад завершена.',
  },
  {
    id: 'quest_emberfall_badlands_dungeon',
    title: 'Данж: Пеплопад',
    giverId: 'qg_emberfall_badlands',
    levelReq: 29,
    zoneId: 'emberfall_badlands',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'emberfall_badlands_dungeon', required: 1 }],
    reward: { xp: 5220, gold: 1595 },
    introText: 'Цель: пройти данж зоны Пеплопад.',
    progressText: 'Пройди данж зоны Пеплопад.',
    completeText: 'Данж зоны Пеплопад пройден.',
  },
  {
    id: 'quest_duskglass_reach_cleanup',
    title: 'Сумрачное Стекло: зачистка',
    giverId: 'qg_duskglass_reach',
    levelReq: 33,
    zoneId: 'duskglass_reach',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['duskglass_reach_stalker', 'duskglass_reach_adept', 'duskglass_reach_sentinel', 'duskglass_reach_wraith'], required: 12 }],
    reward: { xp: 3960, gold: 1155 },
    introText: 'Цель: убить 12 врагов в зоне Сумрачное Стекло.',
    progressText: 'Убей 12 врагов в зоне Сумрачное Стекло.',
    completeText: 'Зачистка зоны Сумрачное Стекло завершена.',
  },
  {
    id: 'quest_duskglass_reach_dungeon',
    title: 'Данж: Сумрачное Стекло',
    giverId: 'qg_duskglass_reach',
    levelReq: 33,
    zoneId: 'duskglass_reach',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'duskglass_reach_dungeon', required: 1 }],
    reward: { xp: 5940, gold: 1815 },
    introText: 'Цель: пройти данж зоны Сумрачное Стекло.',
    progressText: 'Пройди данж зоны Сумрачное Стекло.',
    completeText: 'Данж зоны Сумрачное Стекло пройден.',
  },
  {
    id: 'quest_stormpeak_gate_cleanup',
    title: 'Врата Грозового Пика: зачистка',
    giverId: 'qg_stormpeak_gate',
    levelReq: 37,
    zoneId: 'stormpeak_gate',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['stormpeak_gate_stalker', 'stormpeak_gate_adept', 'stormpeak_gate_sentinel', 'stormpeak_gate_wraith'], required: 12 }],
    reward: { xp: 4440, gold: 1295 },
    introText: 'Цель: убить 12 врагов в зоне Врата Грозового Пика.',
    progressText: 'Убей 12 врагов в зоне Врата Грозового Пика.',
    completeText: 'Зачистка зоны Врата Грозового Пика завершена.',
  },
  {
    id: 'quest_stormpeak_gate_dungeon',
    title: 'Данж: Врата Грозового Пика',
    giverId: 'qg_stormpeak_gate',
    levelReq: 37,
    zoneId: 'stormpeak_gate',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'stormpeak_gate_dungeon', required: 1 }],
    reward: { xp: 6660, gold: 2035 },
    introText: 'Цель: пройти данж зоны Врата Грозового Пика.',
    progressText: 'Пройди данж зоны Врата Грозового Пика.',
    completeText: 'Данж зоны Врата Грозового Пика пройден.',
  },
  {
    id: 'quest_hollow_star_marsh_cleanup',
    title: 'Трясина Пустой Звезды: зачистка',
    giverId: 'qg_hollow_star_marsh',
    levelReq: 41,
    zoneId: 'hollow_star_marsh',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['hollow_star_marsh_stalker', 'hollow_star_marsh_adept', 'hollow_star_marsh_sentinel', 'hollow_star_marsh_wraith'], required: 12 }],
    reward: { xp: 4920, gold: 1435 },
    introText: 'Цель: убить 12 врагов в зоне Трясина Пустой Звезды.',
    progressText: 'Убей 12 врагов в зоне Трясина Пустой Звезды.',
    completeText: 'Зачистка зоны Трясина Пустой Звезды завершена.',
  },
  {
    id: 'quest_hollow_star_marsh_dungeon',
    title: 'Данж: Трясина Пустой Звезды',
    giverId: 'qg_hollow_star_marsh',
    levelReq: 41,
    zoneId: 'hollow_star_marsh',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'hollow_star_marsh_dungeon', required: 1 }],
    reward: { xp: 7380, gold: 2255 },
    introText: 'Цель: пройти данж зоны Трясина Пустой Звезды.',
    progressText: 'Пройди данж зоны Трясина Пустой Звезды.',
    completeText: 'Данж зоны Трясина Пустой Звезды пройден.',
  },
  {
    id: 'quest_crimson_obelisk_cleanup',
    title: 'Багровый Обелиск: зачистка',
    giverId: 'qg_crimson_obelisk',
    levelReq: 45,
    zoneId: 'crimson_obelisk',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['crimson_obelisk_stalker', 'crimson_obelisk_adept', 'crimson_obelisk_sentinel', 'crimson_obelisk_wraith'], required: 12 }],
    reward: { xp: 5400, gold: 1575 },
    introText: 'Цель: убить 12 врагов в зоне Багровый Обелиск.',
    progressText: 'Убей 12 врагов в зоне Багровый Обелиск.',
    completeText: 'Зачистка зоны Багровый Обелиск завершена.',
  },
  {
    id: 'quest_crimson_obelisk_dungeon',
    title: 'Данж: Багровый Обелиск',
    giverId: 'qg_crimson_obelisk',
    levelReq: 45,
    zoneId: 'crimson_obelisk',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'crimson_obelisk_dungeon', required: 1 }],
    reward: { xp: 8100, gold: 2475 },
    introText: 'Цель: пройти данж зоны Багровый Обелиск.',
    progressText: 'Пройди данж зоны Багровый Обелиск.',
    completeText: 'Данж зоны Багровый Обелиск пройден.',
  },
  {
    id: 'quest_pale_king_road_cleanup',
    title: 'Дорога Бледного Короля: зачистка',
    giverId: 'qg_pale_king_road',
    levelReq: 49,
    zoneId: 'pale_king_road',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['pale_king_road_stalker', 'pale_king_road_adept', 'pale_king_road_sentinel', 'pale_king_road_wraith'], required: 12 }],
    reward: { xp: 5880, gold: 1715 },
    introText: 'Цель: убить 12 врагов в зоне Дорога Бледного Короля.',
    progressText: 'Убей 12 врагов в зоне Дорога Бледного Короля.',
    completeText: 'Зачистка зоны Дорога Бледного Короля завершена.',
  },
  {
    id: 'quest_pale_king_road_dungeon',
    title: 'Данж: Дорога Бледного Короля',
    giverId: 'qg_pale_king_road',
    levelReq: 49,
    zoneId: 'pale_king_road',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'pale_king_road_dungeon', required: 1 }],
    reward: { xp: 8820, gold: 2695 },
    introText: 'Цель: пройти данж зоны Дорога Бледного Короля.',
    progressText: 'Пройди данж зоны Дорога Бледного Короля.',
    completeText: 'Данж зоны Дорога Бледного Короля пройден.',
  },
  {
    id: 'quest_voidglass_wastes_cleanup',
    title: 'Пустоши Чёрного Стекла: зачистка',
    giverId: 'qg_voidglass_wastes',
    levelReq: 53,
    zoneId: 'voidglass_wastes',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['voidglass_wastes_stalker', 'voidglass_wastes_adept', 'voidglass_wastes_sentinel', 'voidglass_wastes_wraith'], required: 12 }],
    reward: { xp: 6360, gold: 1855 },
    introText: 'Цель: убить 12 врагов в зоне Пустоши Чёрного Стекла.',
    progressText: 'Убей 12 врагов в зоне Пустоши Чёрного Стекла.',
    completeText: 'Зачистка зоны Пустоши Чёрного Стекла завершена.',
  },
  {
    id: 'quest_voidglass_wastes_dungeon',
    title: 'Данж: Пустоши Чёрного Стекла',
    giverId: 'qg_voidglass_wastes',
    levelReq: 53,
    zoneId: 'voidglass_wastes',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'voidglass_wastes_dungeon', required: 1 }],
    reward: { xp: 9540, gold: 2915 },
    introText: 'Цель: пройти данж зоны Пустоши Чёрного Стекла.',
    progressText: 'Пройди данж зоны Пустоши Чёрного Стекла.',
    completeText: 'Данж зоны Пустоши Чёрного Стекла пройден.',
  },
  {
    id: 'quest_last_sun_plateau_cleanup',
    title: 'Плато Последнего Солнца: зачистка',
    giverId: 'qg_last_sun_plateau',
    levelReq: 57,
    zoneId: 'last_sun_plateau',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['last_sun_plateau_stalker', 'last_sun_plateau_adept', 'last_sun_plateau_sentinel', 'last_sun_plateau_wraith'], required: 12 }],
    reward: { xp: 6840, gold: 1995 },
    introText: 'Цель: убить 12 врагов в зоне Плато Последнего Солнца.',
    progressText: 'Убей 12 врагов в зоне Плато Последнего Солнца.',
    completeText: 'Зачистка зоны Плато Последнего Солнца завершена.',
  },
  {
    id: 'quest_last_sun_plateau_dungeon',
    title: 'Данж: Плато Последнего Солнца',
    giverId: 'qg_last_sun_plateau',
    levelReq: 57,
    zoneId: 'last_sun_plateau',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'last_sun_plateau_dungeon', required: 1 }],
    reward: { xp: 10260, gold: 3135 },
    introText: 'Цель: пройти данж зоны Плато Последнего Солнца.',
    progressText: 'Пройди данж зоны Плато Последнего Солнца.',
    completeText: 'Данж зоны Плато Последнего Солнца пройден.',
  },
  {
    id: 'quest_raid_stormpeak_trial_40',
    title: 'Рейд: Испытание Грозового Пика',
    giverId: 'qg_stormpeak_gate',
    levelReq: 40,
    zoneId: 'stormpeak_gate',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'raid_stormpeak_trial_40', required: 1 }],
    reward: { xp: 10400, gold: 4800 },
    introText: 'Цель: пройти рейд Испытание Грозового Пика. Требование: GS 8200.',
    progressText: 'Пройди рейд Испытание Грозового Пика.',
    completeText: 'Рейд Испытание Грозового Пика пройден.',
  },
  {
    id: 'quest_raid_last_sun_vanguard_60',
    title: 'Рейд: Авангард Последнего Солнца',
    giverId: 'qg_last_sun_plateau',
    levelReq: 60,
    zoneId: 'last_sun_plateau',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'raid_last_sun_vanguard_60', required: 1 }],
    reward: { xp: 15600, gold: 7200 },
    introText: 'Цель: пройти рейд Авангард Последнего Солнца. Требование: GS 10500.',
    progressText: 'Пройди рейд Авангард Последнего Солнца.',
    completeText: 'Рейд Авангард Последнего Солнца пройден.',
  },
  {
    id: 'quest_raid_voidglass_citadel_60',
    title: 'Рейд: Цитадель Чёрного Стекла',
    giverId: 'qg_last_sun_plateau',
    levelReq: 60,
    zoneId: 'last_sun_plateau',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'raid_voidglass_citadel_60', required: 1 }],
    reward: { xp: 15600, gold: 7200 },
    introText: 'Цель: пройти рейд Цитадель Чёрного Стекла. Требование: GS 12500.',
    progressText: 'Пройди рейд Цитадель Чёрного Стекла.',
    completeText: 'Рейд Цитадель Чёрного Стекла пройден.',
  },
  {
    id: 'quest_raid_worldcore_zero_60',
    title: 'Рейд: Нулевое Сердце Мира',
    giverId: 'qg_last_sun_plateau',
    levelReq: 60,
    zoneId: 'last_sun_plateau',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'raid_worldcore_zero_60', required: 1 }],
    reward: { xp: 15600, gold: 7200 },
    introText: 'Цель: пройти рейд Нулевое Сердце Мира. Требование: GS 14500.',
    progressText: 'Пройди рейд Нулевое Сердце Мира.',
    completeText: 'Рейд Нулевое Сердце Мира пройден.',
  }
];
