import type { QuestDefinition } from '../types/game';
import { EXPANSION_QUESTS } from './level60Expansion';
import { UNLOCK_QUESTS } from './unlockQuestlines';

export const QUESTS: QuestDefinition[] = [
  {
    id: 'quest_first_steps',
    title: 'Выйти в поля',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'system',
    objectives: [{ type: 'system', systemAction: 'visit_greenfield', required: 1 }],
    reward: { xp: 60, gold: 20 },
    introText: 'Цель: перейти в Зелёные Поля.',
    progressText: 'Перейди в Зелёные Поля.',
    completeText: 'Зелёные Поля открыты.',
  },

  {
    id: 'quest_green_slime_cleanup',
    title: 'Слизни',
    giverId: 'qg_old_holt',
    levelReq: 1,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'green_slime', required: 8 }],
    reward: { xp: 120, gold: 25, items: [{ itemId: 'minor_potion', amount: 2 }] },
    introText: 'Цель: убить 8 зелёных слизней.',
    progressText: 'Убей 8 зелёных слизней.',
    completeText: 'Убито 8 зелёных слизней.',
  },
  {
    id: 'quest_field_rat_cleanup',
    title: 'Полевые крысы',
    giverId: 'qg_old_holt',
    levelReq: 1,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'field_rat', required: 8 }],
    reward: { xp: 120, gold: 25 },
    introText: 'Цель: убить 8 полевых крыс.',
    progressText: 'Убей 8 полевых крыс.',
    completeText: 'Убито 8 полевых крыс.',
  },
  {
    id: 'quest_boar_mud_cleanup',
    title: 'Кабанья низина',
    giverId: 'qg_old_holt',
    levelReq: 2,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['mud_boar', 'briar_imp'], required: 10 }],
    reward: { xp: 180, gold: 45, items: [{ itemId: 'sharpening_stone', amount: 1 }] },
    introText: 'Цель: убить 10 врагов Кабаньей низины.',
    progressText: 'Убей 10 врагов Кабаньей низины.',
    completeText: 'Убито 10 врагов Кабаньей низины.',
  },

  {
    id: 'quest_redcap_cleanup',
    title: 'Красные колпаки',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['redcap_raider', 'redcap_torchbearer'], required: 10 }],
    reward: { xp: 440, gold: 95 },
    introText: 'Цель: убить 10 красноколпаков.',
    progressText: 'Убей 10 красноколпаков.',
    completeText: 'Убито 10 красноколпаков.',
  },
  {
    id: 'quest_redcap_bruisers',
    title: 'Громилы',
    giverId: 'qg_brigg_colter',
    levelReq: 7,
    zoneId: 'redcap_hills',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'redcap_bruiser', required: 8 }],
    reward: { xp: 520, gold: 120 },
    introText: 'Цель: убить 8 красноколпаков-громил.',
    progressText: 'Убей 8 красноколпаков-громил.',
    completeText: 'Убито 8 красноколпаков-громил.',
  },
  {
    id: 'quest_redcap_cutthroats',
    title: 'Резаки',
    giverId: 'qg_brigg_colter',
    levelReq: 8,
    zoneId: 'redcap_hills',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'redcap_cutthroat', required: 6 }],
    reward: { xp: 600, gold: 150 },
    introText: 'Цель: убить 6 красноколпаков-резаков.',
    progressText: 'Убей 6 красноколпаков-резаков.',
    completeText: 'Убито 6 красноколпаков-резаков.',
  },
  {
    id: 'quest_enter_old_lantern',
    title: 'Подвал Старого Фонаря',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'old_lantern_cellar', required: 1 }],
    reward: { xp: 720, gold: 180 },
    introText: 'Цель: пройти Подвал Старого Фонаря.',
    progressText: 'Пройди Подвал Старого Фонаря.',
    completeText: 'Подвал Старого Фонаря пройден.',
  },

  {
    id: 'quest_ash_leech_cleanup',
    title: 'Пепельные пиявки',
    giverId: 'qg_sera_ash',
    levelReq: 9,
    zoneId: 'ashen_mire',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'ash_mire_leech', required: 8 }],
    reward: { xp: 620, gold: 120 },
    introText: 'Цель: убить 8 пепельных пиявок.',
    progressText: 'Убей 8 пепельных пиявок.',
    completeText: 'Убито 8 пепельных пиявок.',
  },
  {
    id: 'quest_ash_crawler_cleanup',
    title: 'Топяные ползуны',
    giverId: 'qg_sera_ash',
    levelReq: 10,
    zoneId: 'ashen_mire',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'ash_mire_crawler', required: 8 }],
    reward: { xp: 700, gold: 140 },
    introText: 'Цель: убить 8 пепельных ползунов.',
    progressText: 'Убей 8 пепельных ползунов.',
    completeText: 'Убито 8 пепельных ползунов.',
  },
  {
    id: 'quest_ash_guard_watch',
    title: 'Пост стражи',
    giverId: 'qg_sera_ash',
    levelReq: 11,
    zoneId: 'ashen_mire',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['mireglass_caster', 'ash_guard_veteran'], required: 12 }],
    reward: { xp: 760, gold: 160 },
    introText: 'Цель: убить 12 врагов на посту стражи.',
    progressText: 'Убей 12 врагов на посту стражи.',
    completeText: 'Убито 12 врагов на посту стражи.',
  },
  {
    id: 'quest_black_king_watch',
    title: 'Дозор Чёрного Короля',
    giverId: 'qg_sera_ash',
    levelReq: 9,
    zoneId: 'ashen_mire',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'blackroot_watch', required: 1 }],
    reward: { xp: 900, gold: 220 },
    introText: 'Цель: пройти Дозор Чёрного Короля.',
    progressText: 'Пройди Дозор Чёрного Короля.',
    completeText: 'Дозор Чёрного Короля пройден.',
  },

  {
    id: 'quest_moon_wisps',
    title: 'Лунные огоньки',
    giverId: 'qg_lyra_munn',
    levelReq: 13,
    zoneId: 'moonwood',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'moon_wisp', required: 8 }],
    reward: { xp: 900, gold: 180, items: [{ itemId: 'mana_potion', amount: 2 }] },
    introText: 'Цель: убить 8 лунных огоньков.',
    progressText: 'Убей 8 лунных огоньков.',
    completeText: 'Убито 8 лунных огоньков.',
  },
  {
    id: 'quest_moon_stags',
    title: 'Лунные олени',
    giverId: 'qg_lyra_munn',
    levelReq: 14,
    zoneId: 'moonwood',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'moon_stag', required: 8 }],
    reward: { xp: 980, gold: 200 },
    introText: 'Цель: убить 8 лунных оленей.',
    progressText: 'Убей 8 лунных оленей.',
    completeText: 'Убито 8 лунных оленей.',
  },
  {
    id: 'quest_moonroot_shamans',
    title: 'Шаманы корня',
    giverId: 'qg_lyra_munn',
    levelReq: 16,
    zoneId: 'moonwood',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['lunar_bound_guard', 'moonroot_shaman'], required: 10 }],
    reward: { xp: 1100, gold: 260 },
    introText: 'Цель: убить 10 стражей или шаманов Лунного Леса.',
    progressText: 'Убей 10 стражей или шаманов Лунного Леса.',
    completeText: 'Убито 10 стражей или шаманов Лунного Леса.',
  },
  {
    id: 'quest_mire_depths',
    title: 'Глубины Топи',
    giverId: 'qg_lyra_munn',
    levelReq: 13,
    zoneId: 'moonwood',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'mire_depths', required: 1 }],
    reward: { xp: 1200, gold: 300 },
    introText: 'Цель: пройти Глубины Топи.',
    progressText: 'Пройди Глубины Топи.',
    completeText: 'Глубины Топи пройдены.',
  },

  {
    id: 'quest_frost_lynx_hunt',
    title: 'Ледяные рыси',
    giverId: 'qg_sigrid_hale',
    levelReq: 17,
    zoneId: 'frostspire_ridge',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'frost_lynx', required: 8 }],
    reward: { xp: 1300, gold: 260 },
    introText: 'Цель: убить 8 ледяных рысей.',
    progressText: 'Убей 8 ледяных рысей.',
    completeText: 'Убито 8 ледяных рысей.',
  },
  {
    id: 'quest_frost_menders',
    title: 'Синие лекари',
    giverId: 'qg_sigrid_hale',
    levelReq: 17,
    zoneId: 'frostspire_ridge',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'blueglass_mender', required: 8 }],
    reward: { xp: 1350, gold: 280 },
    introText: 'Цель: убить 8 синих лекарей.',
    progressText: 'Убей 8 синих лекарей.',
    completeText: 'Убито 8 синих лекарей.',
  },
  {
    id: 'quest_frost_wraiths',
    title: 'Ледяные призраки',
    giverId: 'qg_sigrid_hale',
    levelReq: 19,
    zoneId: 'frostspire_ridge',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['spire_sellsword', 'frost_wraith'], required: 12 }],
    reward: { xp: 1500, gold: 320 },
    introText: 'Цель: убить 12 наёмников или ледяных призраков.',
    progressText: 'Убей 12 наёмников или ледяных призраков.',
    completeText: 'Убито 12 наёмников или ледяных призраков.',
  },
  {
    id: 'quest_frost_vault',
    title: 'Ледяное Хранилище',
    giverId: 'qg_sigrid_hale',
    levelReq: 17,
    zoneId: 'frostspire_ridge',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'frost_vault', required: 1 }],
    reward: { xp: 1800, gold: 420 },
    introText: 'Цель: пройти Ледяное Хранилище.',
    progressText: 'Пройди Ледяное Хранилище.',
    completeText: 'Ледяное Хранилище пройдено.',
  },

  {
    id: 'quest_wyrmspire_cultists',
    title: 'Культисты Вирмшпиля',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['wyrmspire_cultist', 'wyrmspire_scaleguard'], required: 10 }],
    reward: { xp: 2200, gold: 500 },
    introText: 'Цель: убить 10 культистов или стражей Вирмшпиля.',
    progressText: 'Убей 10 культистов или стражей Вирмшпиля.',
    completeText: 'Убито 10 культистов или стражей Вирмшпиля.',
  },
  {
    id: 'quest_wyrmspire_glassbound',
    title: 'Стеклянные связанные',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['wyrmspire_glassbound', 'glass_catacomb_sage'], required: 10 }],
    reward: { xp: 2350, gold: 560 },
    introText: 'Цель: убить 10 стеклянных связанных или мудрецов.',
    progressText: 'Убей 10 стеклянных связанных или мудрецов.',
    completeText: 'Убито 10 стеклянных связанных или мудрецов.',
  },
  {
    id: 'quest_glass_catacomb',
    title: 'Стеклянные Катакомбы',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'glass_catacomb', required: 1 }],
    reward: { xp: 2600, gold: 650 },
    introText: 'Цель: пройти Стеклянные Катакомбы.',
    progressText: 'Пройди Стеклянные Катакомбы.',
    completeText: 'Стеклянные Катакомбы пройдены.',
  },
  {
    id: 'quest_wyrmspire_raid',
    title: 'Вирмшпиль',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'wyrmspire_first_raid', required: 1 }],
    reward: { xp: 3000, gold: 900, items: [{ itemId: 'enhance_stone_uncommon', amount: 2 }] },
    introText: 'Цель: пройти Вирмшпиль.',
    progressText: 'Пройди Вирмшпиль.',
    completeText: 'Вирмшпиль пройден.',
  },
  ...UNLOCK_QUESTS,
  ...EXPANSION_QUESTS,
];

export const getQuestById = (id: string) => QUESTS.find((quest) => quest.id === id);
