import type { QuestDefinition } from '../types/game';

export const QUESTS: QuestDefinition[] = [
  {
    id: 'quest_first_steps',
    title: 'Выйти в поля',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'system',
    objectives: [{ type: 'system', systemAction: 'visit_greenfield', required: 1 }],
    reward: { xp: 60, gold: 20 },
    introText: 'Цель: посетить Зелёные Поля.',
    progressText: 'Посети Зелёные Поля.',
    completeText: 'Посети Зелёные Поля.',
  },

  {
    id: 'quest_green_slime_cleanup',
    title: 'Слизь на поле',
    giverId: 'qg_old_holt',
    levelReq: 1,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'green_slime', required: 8 }],
    reward: { xp: 120, gold: 25, items: [{ itemId: 'minor_potion', amount: 2 }] },
    introText: 'Цель: убить 8 зелёных слизней.',
    progressText: 'Убей 8 зелёных слизней.',
    completeText: 'Убито 8 зелёных слизней.',
  },
  {
    id: 'quest_field_rat_cleanup',
    title: 'Крысы у дороги',
    giverId: 'qg_old_holt',
    levelReq: 1,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'field_rat', required: 8 }],
    reward: { xp: 120, gold: 25 },
    introText: 'Цель: убить 8 полевых крыс.',
    progressText: 'Убей 8 полевых крыс.',
    completeText: 'Убито 8 полевых крыс.',
  },
  {
    id: 'quest_first_field_trophy',
    title: 'Слизистые остатки',
    giverId: 'qg_old_holt',
    levelReq: 1,
    zoneId: 'greenfield',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'slime_residue', required: 3 }],
    reward: { xp: 160, gold: 0, items: [{ itemId: 'sharpening_stone', amount: 1 }] },
    introText: 'Цель: собрать 3 слизистых остатка.',
    progressText: 'Собери 3 слизистых остатка.',
    completeText: 'Собрано 3 слизистых остатка.',
  },

  {
    id: 'quest_redcap_cleanup',
    title: 'Красные колпаки',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['redcap_raider', 'redcap_torchbearer'], required: 10 }],
    reward: { xp: 440, gold: 95 },
    introText: 'Цель: убить 10 красноколпаков.',
    progressText: 'Убей 10 красноколпаков.',
    completeText: 'Убито 10 красноколпаков.',
  },
  {
    id: 'quest_redcap_key_fragments',
    title: 'Обломки ключа',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'old_lantern_key_fragment', required: 3 }],
    reward: { xp: 500, gold: 0, items: [{ itemId: 'enhance_stone_uncommon', amount: 1 }] },
    introText: 'Цель: собрать 3 обломка ключа.',
    progressText: 'Собери 3 обломка ключа.',
    completeText: 'Собрано 3 обломка ключа.',
  },
  {
    id: 'quest_open_party_finder',
    title: 'Собрать группу',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'system',
    objectives: [{ type: 'system', systemAction: 'open_party_finder', required: 1 }],
    reward: { xp: 200, gold: 30 },
    introText: 'Цель: открыть поиск пати.',
    progressText: 'Открой поиск пати.',
    completeText: 'Поиск пати открыт.',
  },
  {
    id: 'quest_enter_old_lantern',
    title: 'Подвал Старого Фонаря',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'old_lantern_cellar', required: 1 }],
    reward: { xp: 360, gold: 60 },
    introText: 'Цель: пройти Подвал Старого Фонаря.',
    progressText: 'Пройди Подвал Старого Фонаря.',
    completeText: 'Подвал Старого Фонаря пройден.',
  },

  {
    id: 'quest_ash_mire_cleanup',
    title: 'Пепельная пиявка',
    giverId: 'qg_sera_ash',
    levelReq: 9,
    zoneId: 'ashen_mire',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['ash_mire_leech', 'ash_mire_crawler'], required: 10 }],
    reward: { xp: 620, gold: 120 },
    introText: 'Цель: убить 10 тварей Пепельной Топи.',
    progressText: 'Убей 10 тварей Пепельной Топи.',
    completeText: 'Убито 10 тварей Пепельной Топи.',
  },
  {
    id: 'quest_ash_guard_watch',
    title: 'Пост стражи',
    giverId: 'qg_sera_ash',
    levelReq: 10,
    zoneId: 'ashen_mire',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['mireglass_caster', 'ash_guard_veteran'], required: 12 }],
    reward: { xp: 760, gold: 160 },
    introText: 'Цель: убить 12 врагов на посту стражи.',
    progressText: 'Убей 12 врагов на посту стражи.',
    completeText: 'Убито 12 врагов на посту стражи.',
  },
  {
    id: 'quest_black_king_watch',
    title: 'Дозор Чёрного Короля',
    giverId: 'qg_sera_ash',
    levelReq: 9,
    zoneId: 'ashen_mire',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'blackroot_watch', required: 1 }],
    reward: { xp: 900, gold: 220 },
    introText: 'Цель: пройти Дозор Чёрного Короля.',
    progressText: 'Пройди Дозор Чёрного Короля.',
    completeText: 'Дозор Чёрного Короля пройден.',
  },

  {
    id: 'quest_moon_wisps',
    title: 'Лунные огоньки',
    giverId: 'qg_lyra_munn',
    levelReq: 13,
    zoneId: 'moonwood',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['moon_wisp', 'moon_stag'], required: 10 }],
    reward: { xp: 900, gold: 180, items: [{ itemId: 'mana_potion', amount: 2 }] },
    introText: 'Цель: убить 10 существ Лунного Леса.',
    progressText: 'Убей 10 существ Лунного Леса.',
    completeText: 'Убито 10 существ Лунного Леса.',
  },
  {
    id: 'quest_moon_dust',
    title: 'Лунная пыль',
    giverId: 'qg_lyra_munn',
    levelReq: 13,
    zoneId: 'moonwood',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'moon_dust', required: 5 }],
    reward: { xp: 980, gold: 160 },
    introText: 'Цель: собрать 5 лунной пыли.',
    progressText: 'Собери 5 лунной пыли.',
    completeText: 'Собрано 5 лунной пыли.',
  },
  {
    id: 'quest_mire_depths',
    title: 'Глубины Топи',
    giverId: 'qg_lyra_munn',
    levelReq: 13,
    zoneId: 'moonwood',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'mire_depths', required: 1 }],
    reward: { xp: 1200, gold: 300 },
    introText: 'Цель: пройти Глубины Топи.',
    progressText: 'Пройди Глубины Топи.',
    completeText: 'Глубины Топи пройдены.',
  },

  {
    id: 'quest_frost_ridge_hunt',
    title: 'Хребет',
    giverId: 'qg_sigrid_hale',
    levelReq: 17,
    zoneId: 'frostspire_ridge',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['frost_lynx', 'blueglass_mender'], required: 10 }],
    reward: { xp: 1300, gold: 260 },
    introText: 'Цель: убить 10 врагов Ледяного Хребта.',
    progressText: 'Убей 10 врагов Ледяного Хребта.',
    completeText: 'Убито 10 врагов Ледяного Хребта.',
  },
  {
    id: 'quest_frost_contract_camp',
    title: 'Лагерь наёмников',
    giverId: 'qg_sigrid_hale',
    levelReq: 18,
    zoneId: 'frostspire_ridge',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['spire_sellsword', 'frost_wraith'], required: 12 }],
    reward: { xp: 1500, gold: 320 },
    introText: 'Цель: убить 12 врагов в лагере наёмников.',
    progressText: 'Убей 12 врагов в лагере наёмников.',
    completeText: 'Убито 12 врагов в лагере наёмников.',
  },
  {
    id: 'quest_frost_vault',
    title: 'Ледяное Хранилище',
    giverId: 'qg_sigrid_hale',
    levelReq: 17,
    zoneId: 'frostspire_ridge',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'frost_vault', required: 1 }],
    reward: { xp: 1800, gold: 420 },
    introText: 'Цель: пройти Ледяное Хранилище.',
    progressText: 'Пройди Ледяное Хранилище.',
    completeText: 'Ледяное Хранилище пройдено.',
  },

  {
    id: 'quest_wyrmspire_approach',
    title: 'Подступ к Вирмшпилю',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['wyrmspire_cultist', 'wyrmspire_scaleguard', 'wyrmspire_glassbound'], required: 12 }],
    reward: { xp: 2200, gold: 500 },
    introText: 'Цель: убить 12 врагов Вирмшпиля.',
    progressText: 'Убей 12 врагов Вирмшпиля.',
    completeText: 'Убито 12 врагов Вирмшпиля.',
  },
  {
    id: 'quest_glass_catacomb',
    title: 'Стеклянные Катакомбы',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'glass_catacomb', required: 1 }],
    reward: { xp: 2600, gold: 650, items: [{ itemId: 'old_lantern_mark', amount: 1 }] },
    introText: 'Цель: пройти Стеклянные Катакомбы.',
    progressText: 'Пройди Стеклянные Катакомбы.',
    completeText: 'Стеклянные Катакомбы пройдены.',
  },
  {
    id: 'quest_old_lantern_keeper',
    title: 'Первый Вирм',
    giverId: 'qg_arlan_voss',
    levelReq: 20,
    zoneId: 'wyrmspire_peak',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'wyrmspire_first_raid', targetId: 'first_wyrm', required: 1 }],
    reward: { xp: 3000, gold: 900, items: [{ itemId: 'enhance_stone_uncommon', amount: 2 }] },
    introText: 'Цель: пройти Вирмшпиль.',
    progressText: 'Пройди Вирмшпиль.',
    completeText: 'Вирмшпиль пройден.',
  },
];

export const getQuestById = (id: string) => QUESTS.find((quest) => quest.id === id);
