import type { QuestDefinition } from '../types/game';

export const QUESTS: QuestDefinition[] = [
  {
    id: 'quest_first_steps',
    title: 'Первый выход',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'system',
    objectives: [{ type: 'system', systemAction: 'visit_greenfield', required: 1 }],
    reward: { xp: 30, gold: 20 },
    introText: 'Если идёшь за город, начни с поля. Там безопаснее, чем на старой дороге.',
    progressText: 'Выйди в Зелёные Поля.',
    completeText: 'Вернулся? Хорошо. Поля — начало, дальше будет хуже.',
  },
  {
    id: 'quest_green_slime_cleanup',
    title: 'Слизь на тракте',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'green_slime', required: 8 }],
    reward: { xp: 60, gold: 25, items: [{ itemId: 'minor_potion', amount: 2 }] },
    introText: 'Слизь снова выползла к тракту. Возы вязнут, люди ругаются. Убери несколько.',
    progressText: 'Слизь ещё мешает возам.',
    completeText: 'Слизь убрана. Держи оплату.',
  },
  {
    id: 'quest_field_rat_cleanup',
    title: 'Крысы у амбаров',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'field_rat', required: 8 }],
    reward: { xp: 60, gold: 25 },
    introText: 'У амбаров крысы. Обычная работа. Быстро сделаешь — быстро получишь деньги.',
    progressText: 'Крысы всё ещё у амбаров.',
    completeText: 'Амбары целы. Деньги твои.',
  },
  {
    id: 'quest_first_field_trophy',
    title: 'Первый трофей',
    giverId: 'qg_mara_vane',
    levelReq: 1,
    zoneId: 'starting_city',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'slime_residue', required: 3 }],
    reward: { xp: 80, gold: 0, items: [{ itemId: 'sharpening_stone', amount: 1 }] },
    introText: 'Мне нужны остатки слизи. Берут для дешёвых смесей.',
    progressText: 'Принеси три остатка слизи.',
    completeText: 'Подойдёт. Камень забирай.',
  },
  {
    id: 'quest_go_to_old_holt',
    title: 'Старик у дороги',
    giverId: 'qg_mara_vane',
    levelReq: 2,
    zoneId: 'starting_city',
    type: 'talk',
    prerequisiteQuestIds: ['quest_green_slime_cleanup'],
    objectives: [{ type: 'talk', targetId: 'qg_old_holt', required: 1 }],
    reward: { xp: 40, gold: 15 },
    introText: 'На старой дороге сидит Холт. Ворчит, но работу даёт. Сходи к нему.',
    progressText: 'Найди Холта в Зелёных Полях.',
    completeText: 'Мара прислала? Ладно. Работы хватает.',
  },

  {
    id: 'quest_gray_wolf_fence',
    title: 'Волки у изгороди',
    giverId: 'qg_old_holt',
    levelReq: 3,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'gray_wolf', required: 10 }],
    reward: { xp: 100, gold: 45 },
    introText: 'Волки опять у изгороди. Кур таскают. Разгони их.',
    progressText: 'Волки ещё рядом.',
    completeText: 'Шума меньше стало. Нормально.',
  },
  {
    id: 'quest_wolf_pelts',
    title: 'Шкуры для починки',
    giverId: 'qg_old_holt',
    levelReq: 3,
    zoneId: 'greenfield',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'wolf_pelt', required: 5 }],
    reward: { xp: 110, gold: 35, items: [{ itemId: 'minor_potion', amount: 1 }] },
    introText: 'Принеси волчьи шкуры. Дыры в сарае закрыть надо.',
    progressText: 'Пять шкур. Меньше не хватит.',
    completeText: 'Сарай переживёт ещё неделю.',
  },
  {
    id: 'quest_old_road_check',
    title: 'Старая дорога',
    giverId: 'qg_old_holt',
    levelReq: 4,
    zoneId: 'greenfield',
    type: 'kill',
    objectives: [{ type: 'kill', targetIds: ['mud_boar', 'gray_wolf'], required: 12 }],
    reward: { xp: 140, gold: 60 },
    introText: 'Старая дорога опять пустеет. Кабаны, волки, всё вместе. Пройдись там.',
    progressText: 'Дорога ещё грязная.',
    completeText: 'Люди снова пойдут. Пока что.',
  },

  {
    id: 'quest_moon_wisps',
    title: 'Лунные огоньки',
    giverId: 'qg_lyra_munn',
    levelReq: 4,
    zoneId: 'moonwood',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'moon_wisp', required: 8 }],
    reward: { xp: 150, gold: 45, items: [{ itemId: 'mana_potion', amount: 2 }] },
    introText: 'Огоньки подходят к тропе. Они слабые, но людей пугают. Убери несколько.',
    progressText: 'Огоньки ещё у тропы.',
    completeText: 'Теперь тише. Спасибо.',
  },
  {
    id: 'quest_moon_dust',
    title: 'Лунная пыль',
    giverId: 'qg_lyra_munn',
    levelReq: 4,
    zoneId: 'moonwood',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'moon_dust', required: 5 }],
    reward: { xp: 170, gold: 70 },
    introText: 'Мне нужна лунная пыль. Не много. С огоньков хватит.',
    progressText: 'Пять горстей пыли.',
    completeText: 'Да. Этого хватит.',
  },
  {
    id: 'quest_redcap_warning',
    title: 'Красные у холмов',
    giverId: 'qg_lyra_munn',
    levelReq: 5,
    zoneId: 'moonwood',
    type: 'talk',
    prerequisiteQuestIds: ['quest_moon_wisps'],
    objectives: [{ type: 'talk', targetId: 'qg_brigg_colter', required: 1 }],
    reward: { xp: 60, gold: 20 },
    introText: 'Красноколпаки ушли к холмам. Бригг там караван держит. Скажи ему.',
    progressText: 'Найди Бригга в холмах.',
    completeText: 'Лира сказала? Значит, дело дрянь.',
  },

  {
    id: 'quest_redcap_cleanup',
    title: 'Красные колпаки',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'kill',
    objectives: [{ type: 'kill', targetId: 'redcap_raider', required: 10 }],
    reward: { xp: 220, gold: 95 },
    introText: 'Красные колпаки режут мешки и тащат товар. Убей несколько.',
    progressText: 'Они ещё режут мешки.',
    completeText: 'Меньше мелких уродов. Уже лучше.',
  },
  {
    id: 'quest_redcap_key_fragments',
    title: 'Обломки ключа',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'collect',
    objectives: [{ type: 'collect', itemId: 'old_lantern_key_fragment', required: 3 }],
    reward: { xp: 250, gold: 0, items: [{ itemId: 'enhance_stone_uncommon', amount: 1 }] },
    introText: 'У них бывают обломки старого ключа. Найдёшь три — будет проход к Фонарю.',
    progressText: 'Нужны три обломка.',
    completeText: 'Ключ похож на настоящий.',
  },
  {
    id: 'quest_to_old_lantern',
    title: 'К Погребу Старого Фонаря',
    giverId: 'qg_brigg_colter',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'talk',
    prerequisiteQuestIds: ['quest_redcap_key_fragments'],
    objectives: [{ type: 'talk', targetId: 'qg_nathan_rowl', required: 1 }],
    reward: { xp: 80, gold: 40 },
    introText: 'Ключ похож на настоящий. Иди к Погребу Старого Фонаря. Там Натан стоит.',
    progressText: 'Натан стоит у входа.',
    completeText: 'Бригг дал ключ? Тогда слушай.',
  },

  {
    id: 'quest_open_party_finder',
    title: 'Найти группу',
    giverId: 'qg_nathan_rowl',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'system',
    objectives: [{ type: 'system', systemAction: 'open_party_finder', required: 1 }],
    reward: { xp: 100, gold: 30 },
    introText: 'В Погреб одному лучше не лезть. Открой поиск группы и собери людей.',
    progressText: 'Открой поиск пати.',
    completeText: 'Теперь хоть шанс есть.',
  },
  {
    id: 'quest_enter_old_lantern',
    title: 'Первый заход',
    giverId: 'qg_nathan_rowl',
    levelReq: 5,
    zoneId: 'redcap_hills',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'old_lantern_cellar', required: 1 }],
    reward: { xp: 180, gold: 60 },
    introText: 'Зайди в Погреб и посмотри, что там внутри. Если дойдёшь до конца — хорошо.',
    progressText: 'Пройди Погреб Старого Фонаря.',
    completeText: 'Вернулся живой. Уже неплохо.',
  },
  {
    id: 'quest_old_lantern_keeper',
    title: 'Хранитель Фонаря',
    giverId: 'qg_nathan_rowl',
    levelReq: 6,
    zoneId: 'redcap_hills',
    type: 'dungeon',
    objectives: [{ type: 'dungeon', dungeonId: 'old_lantern_cellar', targetId: 'old_lantern_keeper', required: 1 }],
    reward: { xp: 350, gold: 120, items: [{ itemId: 'enhance_stone_uncommon', amount: 1 }, { itemId: 'old_lantern_mark', amount: 1 }] },
    introText: 'Внизу сидит Хранитель. Убей его и принеси знак.',
    progressText: 'Хранитель внизу.',
    completeText: 'Знак настоящий. Про Первый Подъём ещё услышишь.',
  },
];

export const getQuestById = (id: string) => QUESTS.find((quest) => quest.id === id);
