export const QUEST_ITEMS = [
    {
        id: 'slime_residue',
        name: 'Слизистый остаток',
        type: 'material',
        rarity: 'common',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: true,
        price: 2,
        announceIfDropped: false,
        sourceType: 'world',
        sourceName: 'Квесты',
    },
    {
        id: 'wolf_pelt',
        name: 'Волчья шкура',
        type: 'material',
        rarity: 'common',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: true,
        price: 4,
        announceIfDropped: false,
        sourceType: 'world',
        sourceName: 'Квесты',
    },
    {
        id: 'moon_dust',
        name: 'Лунная пыль',
        type: 'material',
        rarity: 'uncommon',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: true,
        price: 8,
        announceIfDropped: false,
        sourceType: 'world',
        sourceName: 'Квесты',
    },
    {
        id: 'old_lantern_key_fragment',
        name: 'Обломок ключа Старого Фонаря',
        type: 'material',
        rarity: 'uncommon',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: false,
        price: 0,
        announceIfDropped: false,
        sourceType: 'world',
        sourceName: 'Квесты',
    },
    {
        id: 'old_lantern_mark',
        name: 'Знак Старого Фонаря',
        type: 'material',
        rarity: 'rare',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: false,
        price: 0,
        announceIfDropped: false,
        sourceType: 'dungeon',
        sourceId: 'old_lantern_cellar',
        sourceName: 'Погреб Старого Фонаря',
    },
    {
        id: 'enhance_stone_uncommon',
        name: 'Зелёный камень усиления',
        type: 'material',
        rarity: 'uncommon',
        levelReq: 1,
        classTags: [],
        stats: {},
        effects: [],
        socketSlots: 0,
        tradeable: true,
        price: 55,
        announceIfDropped: false,
        sourceType: 'world',
        sourceName: 'Квесты',
    },
];
